# Generated by Django 6.0 on 2025-12-06 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_restaurantapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название раздела')),
                ('ordering', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_sections', to='restaurants.restaurant')),
            ],
            options={
                'ordering': ['ordering', 'id'],
            },
        ),
        migrations.AddField(
            model_name='menuitem',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='restaurants.menusection', verbose_name='Раздел меню'),
        ),
    ]
