# Generated by Django 6.0 on 2025-12-06 13:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourierApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=50, verbose_name='Телефон')),
                ('vehicle_type', models.CharField(blank=True, help_text='Например: пешком, велосипед, авто', max_length=50, verbose_name='Тип транспорта')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('status', models.CharField(choices=[('PENDING', 'На рассмотрении'), ('APPROVED', 'Одобрена'), ('REJECTED', 'Отклонена')], default='PENDING', max_length=20, verbose_name='Статус заявки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Обработана')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courier_applications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
